# permissions for end users to view echoservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: echoservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: echo-service-operator
    app.kubernetes.io/part-of: echo-service-operator
    app.kubernetes.io/managed-by: kustomize
  name: echoservice-viewer-role
rules:
- apiGroups:
  - echo-service-operator.davidebianchi.github.io
  resources:
  - echoservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - echo-service-operator.davidebianchi.github.io
  resources:
  - echoservices/status
  verbs:
  - get
